server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default
  application:
    name: hotel-manager
  datasource:
    url: jdbc:mysql://${hotel-manager-db:localhost}:3307/hotel-manager-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update



--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: flight-manager
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: diego
    password: diego
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
